adb push DHL /storage/temp_dir
adb push DHL_TC /storage/temp_dir
adb push mvbt /storage/temp_dir
adb push original /storage/temp_dir
adb push mvbt_opt /storage/temp_dir
adb push off_opt /storage/temp_dir
adb push off_opt_ins /storage/temp_dir
adb push wal_opt /storage/temp_dir
adb push shadow /storage/temp_dir
adb push shadow_x /storage/temp_dir
adb push Sev_DHL /storage/temp_dir
adb push Sev_DHL_TC /storage/temp_dir
adb push Sev_mvbt /storage/temp_dir
adb push Sev_mvbt_opt /storage/temp_dir
adb push Sev_original /storage/temp_dir
adb push Sev_off_opt /storage/temp_dir
adb push Sev_off_opt_ins /storage/temp_dir
adb push Sev_wal_opt /storage/temp_dir
adb push Sev_shadow /storage/temp_dir
adb push Sev_shadow_x /storage/temp_dir
#adb push oper_ratio.sh /storage/temp_dir
#adb push breakdown.sh /storage/temp_dir
#adb push run.sh /storage/temp_dir
#adb push tail.sh /storage/temp_dir
adb push DHL_recovery /storage/temp_dir
adb push mvbt_recovery /storage/temp_dir
adb push original_recovery /storage/temp_dir
adb push shadow_recovery /storage/temp_dir
#adb push recovery.sh /storage/temp_dir
