adb push DHL /cache/test_dir
adb push DHL_TC /cache/test_dir
adb push mvbt_opt /cache/test_dir
adb push mvbt /cache/test_dir
adb push off_opt /cache/test_dir
adb push off_opt_ins /cache/test_dir
adb push wal_opt /cache/test_dir
adb push wal_opt_ins /cache/test_dir
adb push shadow_x /cache/test_dir
adb push shadow_x_ins /cache/test_dir
adb push original /cache/test_dir
adb push wal /cache/test_dir
adb push wal_ins /cache/test_dir
#adb push Sev_DHL /cache/test_dir
#adb push Sev_DHL_TC /cache/test_dir
#adb push Sev_mvbt_opt /cache/test_dir
#adb push Sev_off_opt /cache/test_dir
#adb push Sev_wal_opt /cache/test_dir
#adb push Sev_mvbt /cache/test_dir
#adb push Sev_shadow /cache/test_dir
#adb push Sev_shadow_x /cache/test_dir
#adb push Sev_original /cache/test_dir
adb push oper_ratio.sh /cache/test_dir
adb push breakdown.sh /cache/test_dir
adb push breakdown_opt.sh /cache/test_dir
adb push run.sh /cache/test_dir
adb push tail.sh /cache/test_dir
#adb push DHL_recovery /cache/test_dir
#adb push mvbt_recovery /cache/test_dir
#adb push original_recovery /cache/test_dir
#adb push shadow_recovery /cache/test_dir
adb push recovery.sh /cache/test_dir
